GET http://localhost:3000/todos/?category=HOME 

###
GET http://localhost:3000/todos/2

###
GET http://localhost:3000/agenda/?date=2021-12-12

###
POST http://localhost:3000/todos/?status=poo
Content-Type: application/json 

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}